routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Authentication Routes & Registration Routes
Auth::routes();
Route::get('get-services', 'ServicesController@getServices');
//Route::get('get-pages', 'PagesController@getPages');

$backendRoutes = function () {

    Route::get('/', 'HomeController@dashboard')->middleware('auth');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => ['auth']], function () {

        Route::get('profile/{user}', 'UserController@profile')->name('profile.view');
        Route::post('profile/{user}', 'UserController@profileUpdate')->name('profile.edit');
        Route::post('profile_image_upload/{user}', 'UserController@profileImageUpload')->name('profile.upload');
        
        Route::get('/dashboard', 'HomeController@dashboard');
        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::resource('services', 'ServicesController');
        Route::get('get-all-services', 'ServicesController@getAllServices');


        // Blog Routes
        Route::resource('categories', 'CategoryController', ['except' => ['create']]);
        Route::resource('tags', 'TagController', ['except' => ['create']]);
        Route::resource('posts', 'PostController');

        // Customers
        Route::resource('customers', 'CustomersController');
        Route::get('get-customers', 'CustomersController@getCustomers');

        // Menu
        Route::resource('menu', 'MenuController');
        Route::get('get-menus', 'MenuController@getMenus');

    });
};

$frontendRoutes = function () {
    Route::get('/', 'DemoController@getHome');
    Route::get('/request_demo', 'DemoController@getDemoRequestForm');
    Route::post('/submit_demo_request', 'DemoController@postDemoRequest');
};


Route::group(['domain' => Config::get('app.domains.admin'), 'middleware' => []], $backendRoutes);
Route::group(['domain' => Config::get('app.domains.website'), 'middleware' => []], $frontendRoutes);

app/Models/Tag.php
<?php
/**
 * @Author: Asad Raza
 * @Dated: 15-Oct-2020
 *
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use SoftDeletes;
    protected $table = "tags";

    protected $fillable = [
        'name','created_by','updated_by'
    ];

    public static $tagsRules = [
        "general" => [
            'name' => 'required|max:255'
        ]
    ];

    public function posts()
    {
    	return $this->belongsToMany('App\Models\Post','post_tag','fk_tag_id','fk_post_id');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Tag;
use Session;

class TagController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array('name' => 'required|max:255'));
        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        Session::flash('success', 'New Tag was successfully created!');

        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tag = Tag::with('posts')->find($id);
        return view('tags.show')->withTag($tag);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('tags.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);

        $this->validate($request, ['name' => 'required|max:255']);

        $tag->name = $request->name;
        $tag->save();

        Session::flash('success', 'Successfully saved your new tag!');

        return redirect()->route('tags.show', $tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->posts()->detach();

        $tag->delete();

        Session::flash('success', 'Tag was deleted successfully');

        return redirect()->route('tags.index');
    }
}

resources/views/tags/edit.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">

            {{ Form::model($tag, ['route' => ['tags.update', $tag->id], 'method' => "PUT"]) }}

            {{ Form::label('name', "Title:") }}
            {{ Form::text('name', null, ['class' => 'form-control']) }}

            {{ Form::submit('Save Changes', ['class' => 'btn btn-success', 'style' => 'margin-top:20px;']) }}
            {{ Form::close() }}
        </div>
    </section>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-8">
                    <h1>Tags</h1>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach ($tags as $tag)
                            <tr>
                                <th>{{ $tag->id }}</th>
                                <td><a href="{{ route('tags.show', $tag->id) }}">{{ $tag->name }}</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div> <!-- end of .col-md-8 -->

                <div class="col-md-3">
                    <div class="well">
                        {!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}
                        <h2>New Tag</h2>
                        {{ Form::label('name', 'Name:') }}
                        {{ Form::text('name', null, ['class' => 'form-control']) }}

                        {{ Form::submit('Create New Tag', ['class' => 'btn btn-primary btn-block btn-h1-spacing']) }}

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/tags/show.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-8">
                    <h1>{{ $tag->name }} Tag
                        <small>{{ $tag->posts()->count() }} Posts</small>
                    </h1>
                </div>
                <div class="col-md-2">
                    <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-primary pull-right btn-block"
                       style="margin-top:20px;">Edit</a>
                </div>
                <div class="col-md-2">
                    {{ Form::open(['route' => ['tags.destroy', $tag->id], 'method' => 'DELETE']) }}
                    {{ Form::submit('Delete', ['class' => 'btn btn-danger btn-block', 'style' => 'margin-top:20px;']) }}
                    {{ Form::close() }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Tags</th>
                            <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach ($tag->posts as $post)
                            <tr>
                                <th>{{ $post->id }}</th>
                                <td>{{ $post->title }}</td>
                                <td>@foreach ($post->tags as $tag)
                                        <span class="label label-default">{{ $tag->name }}</span>
                                    @endforeach
                                </td>
                                <td><a href="{{ route('posts.show', $post->id ) }}"
                                       class="btn btn-default btn-xs">View</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

@endsection