routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Authentication Routes & Registration Routes
Auth::routes();
Route::get('get-services', 'ServicesController@getServices');
//Route::get('get-pages', 'PagesController@getPages');

$backendRoutes = function () {

    Route::get('/', 'HomeController@dashboard')->middleware('auth');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => ['auth']], function () {

        Route::get('profile/{user}', 'UserController@profile')->name('profile.view');
        Route::post('profile/{user}', 'UserController@profileUpdate')->name('profile.edit');
        Route::post('profile_image_upload/{user}', 'UserController@profileImageUpload')->name('profile.upload');
        
        Route::get('/dashboard', 'HomeController@dashboard');
        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::resource('services', 'ServicesController');
        Route::get('get-all-services', 'ServicesController@getAllServices');


        // Blog Routes
        Route::resource('categories', 'CategoryController', ['except' => ['create']]);
        Route::resource('tags', 'TagController', ['except' => ['create']]);
        Route::resource('posts', 'PostController');

        // Customers
        Route::resource('customers', 'CustomersController');
        Route::get('get-customers', 'CustomersController@getCustomers');

        // Menu
        Route::resource('menu', 'MenuController');
        Route::get('get-menus', 'MenuController@getMenus');

    });
};

$frontendRoutes = function () {
    Route::get('/', 'DemoController@getHome');
    Route::get('/request_demo', 'DemoController@getDemoRequestForm');
    Route::post('/submit_demo_request', 'DemoController@postDemoRequest');
};


Route::group(['domain' => Config::get('app.domains.admin'), 'middleware' => []], $backendRoutes);
Route::group(['domain' => Config::get('app.domains.website'), 'middleware' => []], $frontendRoutes);

app/Models/Services.php
<?php
/**
 * @Author: Asad Raza
 * @Dated: 15-Oct-2020
 *
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Services extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    use SoftDeletes;

    protected $primaryKey = 'services_id';
    protected $table = "services";

    protected $fillable = [
        'services_name', 'services_short_description', 'services_full_description', 'services_image_url','slug', 'created_by', 'updated_by'
    ];

    public static $servicesRules = [
        "general" => [
            'services_name' => 'required',
            'services_short_description' => 'required',
            'slug' => 'required',
        ]
    ];

    public static function getServicesList()
    {
        $services = self::latest()->paginate(5);
        return $services;
    }


    public static function getServicesByFilters($filter)
    {
        $data = Self::orderBy('services_id', 'DESC');
        if (count($filter)) {
            // apply filter if any in future
        }
        return $data->get();
    }


    public static function getServicesPluckList()
    {
        $services = self::pluck("services_name","services_id");
        return $services;
    }


    public static function createService($input)
    {
        self::create($input);
        return true;
    }

    public static function getServicesById($id)
    {
        $services = self::find($id);
        return $services;
    }

    public static function updateService($id, $update)
{
    $services = self::find($id);
    $services->update($update);
    return true;
}

    public static function deleteService($id, $user_id)
    {
        $services = self::find($id);
        $services->deleted_by = $user_id;
        $services->save();
        $services->delete();
    }

}

app/Http/Controllers/ServicesController.php
<?php
/**
 * @Author: Asad Raza
 * @Dated: 15-Oct-2020
 *
 */

namespace App\Http\Controllers;

use App\Models\Services;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Helper;
use App\Helpers\ResponseHandler;
use Log;
use DB;
use URL;

class ServicesController extends Controller
{

    function __construct()
    {

    }

    public function index()
    {

        $this->checkPermission('services-list');
        $services = Services::getServicesList();
        $path = Helper::getStaticPath();
        return view('services.index', compact('services','path'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function getAllServices(Request $request)
    {
        try {
            $filter = $request->all();
            $services = Services::getServicesByFilters($filter);
            return $this->makeDatatable($services);
        } catch (\Exception $e) {
            return ResponseHandler::serverError($e);
        }
    }

    public function makeDatatable($data)
    {
        return \DataTables::of($data)
            ->addColumn('services_id', function ($rowdata) {
                $return = '<td><a target="_blank" href="' . URL::to("/services/$rowdata->services_id") . '">' . $rowdata->services_id . '</a></td>';
                return $return;
            })

            ->addColumn('services_image_url', function ($rowdata) {
                $return = '<td><image width="100%" src="'.Helper::getStaticPath().$rowdata->services_image_url.'"/></td>';
                return $return;
            })

            ->addColumn('created_at', function ($rowdata) {
                $return = date('M j, Y h:ia', strtotime($rowdata->created_at));
                return $return;
            })
            ->addColumn('action', function ($rowdata) {
                $return = '';
                $return .='&nbsp;<a href="' .route('services.edit',$rowdata->services_id).'"><i class="fas fa-edit"></i></a>';
                $return .='&nbsp;<a href="#" onclick="deleteMenu('.$rowdata->services_id.');return false;"><i class="fas fa-trash"></i></a>';
                return $return;
            })
            ->rawColumns(['services_image_url','services_id','action'])
            ->make(true);
    }




    public function create()
    {
        $this->checkPermission('services-create');
        return view('services.create');
    }

    public function store(Request $request)
    {

        $this->checkPermission('services-create');
        $validationErrors = Helper::validationErrors($request, Services::$servicesRules["general"]);
        if ($validationErrors) {
            return back()->withErrors($validationErrors)->withInput($request->all());
        }
        try {
            $request->request->add(['created_by' => Auth::user()->id]);
            if ($request->hasFile('services_image')) {
                $image = $request->file('services_image');
                $filename = time() . '.' . $image->getClientOriginalExtension();
                $file_path = '/services_images/';
                $resize["width"] = 179;
                $resize["height"] = 179;
                Helper::uploadImage($image, $file_path, $filename, $resize);
                $request->request->add(['services_image_url' => $file_path . $filename]);
            }

            Services::createService($request->all());
            return redirect()->route('services.index')
                ->with('success', __('messages.services.created'));
        } catch (\Exception $e) {
            Log::info($e);
            return back()->withErrors(__('messages.general.crashed'))->withInput($request->all());
        }

    }

    public function show($services_id)
    {
        $this->checkPermission('services-list');
        $services = Services::getServicesById($services_id);
        $path = Helper::getStaticPath();
        $services->services_image_url = $path.$services->services_image_url;
        return view('services.show', compact('services'));
    }

    public function edit($services_id)
    {
        $this->checkPermission('services-edit');
        $services = Services::getServicesById($services_id);
        $path = Helper::getStaticPath();
        $services->services_image_url = $path.$services->services_image_url;
        return view('services.edit', compact('services'));
    }

    public function update(Request $request, $services_id)
    {
        $this->checkPermission('services-edit');
        $validationErrors = Helper::validationErrors($request, Services::$servicesRules["general"]);
        if ($validationErrors) {
            return back()->withErrors($validationErrors)->withInput($request->all());
        }
        try {
            $request->request->add(['updated_by' => Auth::user()->id]);
            if ($request->hasFile('services_image')) {
                $image = $request->file('services_image');
                $filename = time() . '.' . $image->getClientOriginalExtension();
                $file_path = '/services_images/';
                $resize["width"] = 179;
                $resize["height"] = 179;
                Helper::uploadImage($image, $file_path, $filename, $resize);
                $request->request->add(['services_image_url' => $file_path . $filename]);
            }
            Services::updateService($services_id, $request->all());
            return redirect()->route('services.index')
                ->with('success', __('messages.services.updated'));
        } catch (\Exception $e) {
            Log::info($e);
            return back()->withErrors(__('messages.general.crashed'))->withInput($request->all());
        }
    }

    public function destroy($services_id)
    {
        $this->checkPermission('services-delete');
        DB::beginTransaction();
        try {
            Services::deleteService($services_id, Auth::user()->id);
            DB::commit();
            return redirect()->route('services.index')
                ->with('success', __('messages.services.deleted'));
        } catch (\Exception $e) {
            DB::rollback();
            Log::info($e);
            return redirect()->route('services.index')->withErrors(__('messages.general.crashed'));
        }
    }

    public function getServices()
    {
        try{
            $services = Services::getServicesPluckList();
            return ResponseHandler::success($services,'');
        } catch (\Exception $e) {
            return ResponseHandler::serverError($e);
        }
    }


}

resources/views/services/create.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Add New Services
                            <a class="btn btn-primary" style="float:right;" href="{{ route('services.index') }}">
                                Back</a>
                        </h2>
                        <hr>

                    </div>

                </div>
            </div>

            <!-- ALERTS STARTS HERE -->
            <section>
                <div class="row">
                    @include('common.alerts')
                </div>
            </section>
            <!-- ALERTS ENDS HERE -->

            {{--<form action="{{ route('services.store') }}" data-parsley-validate = '' files = true method="POST">--}}
                {!! Form::open(array('route' => 'services.store', 'data-parsley-validate' => '', 'files' => true)) !!}
                @csrf


                <div class="row card-body">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Service Name:</strong>
                            <input type="text" name="services_name" class="form-control" placeholder="Service Name" required>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Short Description:</strong>
                            <textarea class="form-control" style="" name="services_short_description"
                                      placeholder="Short Description" required></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Slug:</strong>
                            {{ Form::text('slug', null, array('placeholder'=>"Slug",'class' => 'form-control', 'required' => '', 'minlength' => '5', 'maxlength' => '255') ) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Full Description:</strong>
                            <textarea class="form-control" style="height:150px" name="services_full_description"
                                      placeholder="Full Description" required></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Image:</strong>
                            {{ Form::file('services_image',array('required'=>"true")) }}
                            {{--<input type="text" name="services_image_url" class="form-control" placeholder="Image Url">--}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 ">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>


            </form>

        </div>
    </section>

@endsection

resources/views/services/edit.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Edit Service
                            <a class="btn btn-primary" style="float:right;" href="{{ route('services.index') }}">
                                Back</a>
                        </h2>
                    </div>
                </div>
            </div>


            <!-- ALERTS STARTS HERE -->
            <section>
                <div class="row">
                    @include('common.alerts')
                </div>
            </section>
            <!-- ALERTS ENDS HERE -->


            <form action="{{ route('services.update',$services->services_id) }}" accept-charset="UTF-8" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')


                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Name:</strong>
                            <input type="text" name="services_name" value="{{ $services->services_name }}"
                                   class="form-control"
                                   placeholder="Services Name">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Short Description:</strong>
                            <textarea class="form-control" style="height:150px" name="services_short_description"
                                      placeholder="Short Description">{{ $services->services_short_description }}</textarea>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Slug:</strong>
                            {{ Form::text('slug', $services->slug , array('placeholder'=>"Slug",'class' => 'form-control', 'required' => '', 'minlength' => '5', 'maxlength' => '255') ) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Full Description:</strong>
                            <textarea class="form-control" style="height:150px" name="services_full_description"
                                      placeholder="Full Description">{{ $services->services_full_description }}</textarea>
                        </div>
                    </div>


                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Upload a Featured Image:</strong>
                            {{ Form::file('services_image') }}

                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <image width="30%" height="30%" src="{{$services->services_image_url}}"/>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12 ">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>


            </form>
        </div>
    </section>

@endsection

resources/views/services/index.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Services
                            @can('services-create')
                                <a class="btn btn-success" style="float:right;" href="{{ route('services.create') }}">
                                    Create New Service</a>
                            @endcan
                        </h2>
                    </div>
                    <div class="pull-right">

                    </div>
                </div>
            </div>

            <!-- ALERTS STARTS HERE -->
            <section>
                <div class="row">
                    @include('common.alerts')
                </div>
            </section>
            <!-- ALERTS ENDS HERE -->

            <div class="row">
                <div class="col-md-12">
                    <table id="services_table" class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Service Id</th>
                            <th>Image</th>
                            <th>Services Name</th>
                            <th>Short Description</th>
                            <th>Full Description</th>
                            <th>Slug</th>
                            <th>Created At</th>
                            <th >Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </section>

    <script>

        $(function () {

            var table_name = "services_table";
            var url = "{{ URL::to('/get-all-services') }}";
            var coloumns = [
                {data: 'services_id', name: 'services_id'},
                {data: 'services_image_url', name: 'services_image_url'},
                {data: 'services_name', name: 'services_name'},
                {data: 'services_short_description', name: 'services_short_description'},
                {data: 'services_full_description', name: 'services_full_description'},
                {data: 'slug', name: 'slug'},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action'}
            ];
            var postdata = [];

            CreateDataTableIns(table_name, url, coloumns, postdata);
        });

        function deleteService(id) {
            var formData = {"_token": "{{ csrf_token() }}"};
            var url = "/services/" + id;
            ajax_call("DELETE", url, formData, function (res) {
                location.href = "";
            }, function (res) {
                var json = JSON.parse(res.responseText);
                console.log(json.body);
            });
        }
    </script>

@endsection

resources/views/services/show.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2> Show Service
                            <a class="btn btn-primary" style="float:right;" href="{{ route('services.index') }}">
                                Back</a>
                        </h2>

                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Services Name:</strong>
                        {{ $services->services_name }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Services Short Description:</strong>
                        {{ $services->services_short_description }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Services Full Description:</strong>
                        {{ $services->services_full_description }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Services Slug:</strong>
                        {{ $services->slug }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Image:</strong>
                        <image  src="{{$services->services_image_url}}"/>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection