routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Authentication Routes & Registration Routes
Auth::routes();
Route::get('get-services', 'ServicesController@getServices');
//Route::get('get-pages', 'PagesController@getPages');

$backendRoutes = function () {

    Route::get('/', 'HomeController@dashboard')->middleware('auth');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => ['auth']], function () {

        Route::get('profile/{user}', 'UserController@profile')->name('profile.view');
        Route::post('profile/{user}', 'UserController@profileUpdate')->name('profile.edit');
        Route::post('profile_image_upload/{user}', 'UserController@profileImageUpload')->name('profile.upload');
        
        Route::get('/dashboard', 'HomeController@dashboard');
        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::resource('services', 'ServicesController');
        Route::get('get-all-services', 'ServicesController@getAllServices');


        // Blog Routes
        Route::resource('categories', 'CategoryController', ['except' => ['create']]);
        Route::resource('tags', 'TagController', ['except' => ['create']]);
        Route::resource('posts', 'PostController');

        // Customers
        Route::resource('customers', 'CustomersController');
        Route::get('get-customers', 'CustomersController@getCustomers');

        // Menu
        Route::resource('menu', 'MenuController');
        Route::get('get-menus', 'MenuController@getMenus');

    });
};

$frontendRoutes = function () {
    Route::get('/', 'DemoController@getHome');
    Route::get('/request_demo', 'DemoController@getDemoRequestForm');
    Route::post('/submit_demo_request', 'DemoController@postDemoRequest');
};


Route::group(['domain' => Config::get('app.domains.admin'), 'middleware' => []], $backendRoutes);
Route::group(['domain' => Config::get('app.domains.website'), 'middleware' => []], $frontendRoutes);

app/Models/Menu.php
<?php
/**
 * @Author: Asad Raza
 * @Dated: 15-Oct-2020
 *
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Menu extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    use SoftDeletes;

    protected $primaryKey = 'id';
    protected $table = "menu";

    protected $fillable = [
        'id_parent', 'name', 'link_type','link_id', 'link_detail', 'is_active', 'sort_order', 'created_by', 'updated_by'
    ];

    public static $menuRules = [
        "general" => [
            'name' => 'required',
        ]
    ];

    public static function getMenusByFilters($filter)
    {
        $data = Self::orderBy('id', 'DESC');
        if (count($filter)) {
            // apply filter if any in future
        }
        return $data->get();
    }

    public static function getParentMenu(){
        return Self::where('is_active', '1')
                    ->where('id_parent', 0)->pluck('name','id')->toArray();
    }

    public static function createMenu($input)
    {
        $input["link_id"] = is_null($input["link_id"]) ? 0 : $input["link_id"];
        self::create($input);
        return true;
    }


    public static function getMenuById($id)
    {
        $menu = self::find($id);
        return $menu;
    }

    public static function updateMenu($id, $update)
    {
        $menu = self::find($id);
        $update["link_id"] = is_null($update["link_id"]) ? 0 : $update["link_id"];
        $menu->update($update);
        return true;
    }

    public static function deleteMenu($id, $user_id)
    {
        $menu = self::find($id);
        $menu->deleted_by = $user_id;
        $menu->save();
        $menu->delete();
    }
}

app/Http/Controllers/MenuController.php
<?php
/**
 * @Author: Asad Raza
 * @Dated: 15-Oct-2020
 *
 */

namespace App\Http\Controllers;

use App\Models\Menu;
use App\Models\Services;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Helper;
use App\Helpers\ResponseHandler;
use Log;
use DB;
use URL;
use App\Helpers\Constant;

class MenuController extends Controller
{

    function __construct()
    {

    }

    public function index()
    {
        $this->checkPermission('menu-list');
        return view('menu.index');
    }

    public function getMenus(Request $request)
    {
        try {
            $filter = $request->all();
            $menu = Menu::getMenusByFilters($filter);
            return $this->makeDatatable($menu);
        } catch (\Exception $e) {
            return ResponseHandler::serverError($e);
        }
    }

    public function makeDatatable($data)
    {
        return \DataTables::of($data)
            ->addColumn('id', function ($rowdata) {
                $return = '<td><a target="_blank" href="' . URL::to("/menu/$rowdata->id") . '">' . $rowdata->id . '</a></td>';
                return $return;
            })
            ->addColumn('name', function ($rowdata) {
                $return = $rowdata->name;
                return $return;
            })
            ->addColumn('is_active', function ($rowdata) {
                $return = "";
                if($rowdata->is_active)
                {
                    $return .= "<label class='badge badge-success'>Active</label>";
                }else{
                    $return .= "<label class='badge badge-info'>In Active</label>";
                }
                return $return;
            })
            ->addColumn('link_detail', function ($rowdata) {
                $return = "";
                if($rowdata->link_type == "service")
                {
                    $serviceObj = Services::getServicesById($rowdata->link_id);
                    $return .= "$serviceObj->slug";
                }else if($rowdata->link_type == "link"){
                    $return .= "$rowdata->link_detail";
                }
                return $return;
            })
            ->addColumn('created_at', function ($rowdata) {
                $return = date('M j, Y h:ia', strtotime($rowdata->created_at));
                return $return;
            })
            ->addColumn('action', function ($rowdata) {
                $return = '';
                $return .='&nbsp;<a href="' .route('menu.edit',$rowdata->id).'"><i class="fas fa-edit"></i></a>';
                $return .='&nbsp;<a href="#" onclick="deleteMenu('.$rowdata->id.');return false;"><i class="fas fa-trash"></i></a>';
               return $return;
            })
            ->rawColumns(['name','is_active','id','action'])
            ->make(true);
    }


    public function create()
    {
        $this->checkPermission('menu-create');
        $link_type = Constant::LINK_TYPES;
        $status = Constant::MENU_STATUS;
        $parent_menus = Menu::getParentMenu();
        return view('menu.create',compact("link_type","status",'parent_menus'));
    }

    public function store(Request $request)
    {

        $this->checkPermission('menu-create');
        $validationErrors = Helper::validationErrors($request, Menu::$menuRules["general"]);
        if ($validationErrors) {
            return back()->withErrors($validationErrors)->withInput($request->all());
        }
        try {
            $request->request->add(['created_by' => Auth::user()->id]);
            Menu::createMenu($request->all());
            return redirect()->route('menu.index')
                ->with('success', __('messages.menu.created'));
        } catch (\Exception $e) {
            Log::info($e);
            return back()->withErrors(__('messages.general.crashed'))->withInput($request->all());
        }

    }

    public function show($id)
    {
        $this->checkPermission('menu-list');
        $menu = Menu::getMenuById($id);
        return view('menu.show', compact('menu'));
    }

    public function edit($id)
    {
        $this->checkPermission('menu-edit');
        $menu = Menu::getMenuById($id);
        $link_type = Constant::LINK_TYPES;
        $status = Constant::MENU_STATUS;
        $parent_menus = Menu::getParentMenu();
        return view('menu.edit', compact('parent_menus','menu','link_type','status'));
    }

    public function update(Request $request, $id)
    {
        $this->checkPermission('menu-edit');
        $validationErrors = Helper::validationErrors($request, Menu::$menuRules["general"]);
        if ($validationErrors) {
            return back()->withErrors($validationErrors)->withInput($request->all());
        }
        try {
            $request->request->add(['updated_by' => Auth::user()->id]);
            Menu::updateMenu($id, $request->all());
            return redirect()->route('menu.index')
                ->with('success', __('messages.menu.updated'));
        } catch (\Exception $e) {
            Log::info($e);
            return back()->withErrors(__('messages.general.crashed'))->withInput($request->all());
        }
    }

    public function destroy($id)
    {
        $this->checkPermission('menu-delete');
        DB::beginTransaction();
        try {
            Menu::deleteMenu($id, Auth::user()->id);
            DB::commit();
            return ResponseHandler::success(__('messages.menu.deleted'));
        } catch (\Exception $e) {
            return ResponseHandler::serverError($e);
        }
    }
}

resources/views/menu/create.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Add New Menu
                            <a class="btn btn-primary" style="float:right;" href="{{ route('menu.index') }}">
                                Back</a>
                        </h2>

                    </div>

                </div>
            </div>

            <!-- ALERTS STARTS HERE -->
            <section>
                <div class="row">
                    @include('common.alerts')
                </div>
            </section>


            <form action="{{ route('menu.store') }}" method="POST">
                @csrf
                <div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Select Parent:</strong>
                            <select  class="form-control" name="id_parent" id="id_parent">
                                <option value='0'>Select menu</option>
                                @foreach($parent_menus as $key => $name)
                                    <option value='{{ $key }}'>{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Menu Name:</strong>
                            <input type="text" name="name" class="form-control" placeholder="Menu Name">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Link Type:</strong>
                            <select onchange = "getLinksByValue(this.value)" class="form-control" name="link_type" id="link_type">
                                @foreach($link_type as $key => $name)
                                    <option value='{{ $key }}'>{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            {{ Form::select('link_id', ['' => 'Select'],null, array("id" =>"link_id",'class' => 'form-control','style'=>'display:none')) }}
                            <input type="text" name="link_detail"  placeholder="Insert Link" id="link_detail" class="form-control" style ='display:none' >
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Status:</strong>
                            <select class="form-control" name="is_active">
                                @foreach($status as $key => $name)
                                    <option {{ ($key == '1')?'selected':''}} value='{{ $key }}'>{{ $name }}</option>
                                @endforeach
                            </select>

                        </div>
                    </div>
                    <div class="col-xs-2 col-sm-2 col-md-2">
                        <div class="form-group">
                            <strong>Sort Order:</strong>
                            <input type="text" name="sort_order" class="form-control col-sm" placeholder="">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 ">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>


            </form>

        </div>
    </section>
@section('js')
    <script type="text/javascript">

        {{--$(function () {--}}
            {{--getProvincesByCountryId({{isset($mer_buss_setting->country)?$mer_buss_setting->country:null}})--}}
            {{--getCitiesByProvinceId({{isset($mer_buss_setting->province)?$mer_buss_setting->province:null}})--}}
        {{--});--}}
        getLinksByValue($("#link_type").val());

        function fileDropdown(dd_id, options, first_value) {
            $("#link_detail").hide();
            $("#" + dd_id).find('option').remove();
            $("#" + dd_id).show();
            $("#" + dd_id).append(new Option(first_value, ''));
            $.each(options, function (key, value) {
                $("#" + dd_id).append(new Option(value, key));
            });
        }

        function getLinksByValue(value) {
            if(value == "page"){
                alert("page");
//                var formData = {};
//                var url = "/get-pages";
//                ajax_call("GET", url, formData, function (res) {
//                    fileDropdown('link_id', res.body, 'Select '+value);
//                }, function (res) {
//                    var json = JSON.parse(res.responseText);
//                    console.log(json.body);
//                });
            }else if(value == "service"){
                var formData = {};
                var url = "/get-services";
                ajax_call("GET", url, formData, function (res) {
                    fileDropdown('link_id', res.body, 'Select '+value);
                }, function (res) {
                    var json = JSON.parse(res.responseText);
                    console.log(json.body);
                });

            }else{
                $("#link_id").hide();
                $("#link_detail").show();
            }


        }
    </script>
@stop
@endsection

resources/views/menu/edit.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Edit MENU
                            <a class="btn btn-primary" style="float:right;" href="{{ route('menu.index') }}">
                                Back</a>
                        </h2>
                    </div>
                </div>
            </div>


            <!-- ALERTS STARTS HERE -->
            <section>
                <div class="row">
                    @include('common.alerts')
                </div>
            </section>
            <!-- ALERTS ENDS HERE -->


            {!! Form::model($menu, ['route' => ['menu.update', $menu->id], 'method' => 'PUT','data-parsley-validate' => '', 'files' => true]) !!}

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Select Parent:</strong>
                        {{ Form::select('id_parent', ['' => 'Select menu'] + $parent_menus, null, ['class' => 'form-control'])}}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Menu Name:</strong>
                        {{ Form::text('name', null, ["class" => 'form-control ']) }}
                        {{--<input type="text" name="name" class="form-control" placeholder="Menu Name">--}}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Link Type:</strong>
                        {{ Form::select('link_type', $link_type, null, ['onchange' => "getLinksByValue(this.value)",'id'=>'link_type','class' => 'form-control']) }}

                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        {{ Form::select('link_id', ['' => 'Select'],null, array("id" =>"link_id",'class' => 'form-control','style'=>'display:none')) }}
                        <input type="text" name="link_detail"  placeholder="Insert Link" id="link_detail" class="form-control" style ='display:none' >
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Status:</strong>
                        {{ Form::select('is_active', $status, null, ['class' => 'form-control']) }}
                    </div>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2">
                    <div class="form-group">
                        <strong>Sort Order:</strong>
                        {{ Form::text('sort_order', null, ["class" => 'form-control ']) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 ">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>


            </form>
        </div>
    </section>
@section('js')
    <script type="text/javascript">

        {{--$(function () {--}}
            {{--getProvincesByCountryId({{isset($mer_buss_setting->country)?$mer_buss_setting->country:null}})--}}
            {{--getCitiesByProvinceId({{isset($mer_buss_setting->province)?$mer_buss_setting->province:null}})--}}
        {{--});--}}
        getLinksByValue($("#link_type").val());

        function fileDropdown(dd_id, options, first_value,selected_value) {
            alert(dd_id);
            $("#link_detail").hide();
            $("#" + dd_id).find('option').remove();
            $("#" + dd_id).show();
            $("#" + dd_id).append(new Option(first_value, ''));
            $.each(options, function (key, value) {
                if(key == selected_value) {
                    $("#" + dd_id).append(new Option(value, key, true, true));
                } else {
                    $("#" + dd_id).append(new Option(value, key));
                }
            });
        }

        function getLinksByValue(value) {
            if (value == "page") {
                alert("page");
//                var formData = {};
//                var url = "/get-pages";
//                ajax_call("GET", url, formData, function (res) {
//                    fileDropdown('link_id', res.body, 'Select '+value);
//                }, function (res) {
//                    var json = JSON.parse(res.responseText);
//                    console.log(json.body);
//                });
            } else if (value == "service") {
                const link_id = '{{isset($menu->link_id)?$menu->link_id:null}}';
                var formData = {};
                var url = "/get-services";
                ajax_call("GET", url, formData, function (res) {
                    fileDropdown('link_id', res.body, 'Select ' + value,link_id);
                }, function (res) {
                    var json = JSON.parse(res.responseText);
                    console.log(json.body);
                });

            } else {
                $("#link_id").hide();
                $("#link_detail").show();
            }

        }
    </script>
@stop
@endsection

resources/views/menu/index.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-right">
                        <h2>Menu
                            @can('services-create')
                                <a class="btn btn-success" style="float:right;" href="{{ route('menu.create') }}"> Create New Menu</a>
                            @endcan
                        </h2>
                    </div>
                </div>
            </div>

            <!-- ALERTS STARTS HERE -->
            <section>
                <div class="row">
                    @include('common.alerts')
                </div>
            </section>
            <!-- ALERTS ENDS HERE -->

            <div class="row">
                <div class="col-md-12">
                    <table id="menu_table" class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Menu Id</th>
                            <th>Name</th>
                            <th>Link Type</th>
                            <th>Link Slug</th>
                            <th>Status</th>
                            <th>Sort Order</th>
                            <th>Created At</th>
                            <th width="90px">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
        function deleteMenu(id){
            
            var formData = {"_token": "{{ csrf_token() }}"};
            var url = "/menu/"+id;
            ajax_call("DELETE", url, formData, function (res) {
                location.href = "";
            }, function (res) {
                var json = JSON.parse(res.responseText);
                console.log(json.body);
            });
        }

        $(function () {

            var table_name = "menu_table";
            var url = "{{ URL::to('/get-menus') }}";
            var coloumns = [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'link_type', name: 'link_type'},
                {data: 'link_detail', name: 'link_detail'},
                {data: 'is_active', name: 'is_active'},
                {data: 'sort_order', name: 'sort_order'},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action'}
            ];
            var postdata = [];

            CreateDataTableIns(table_name, url, coloumns, postdata);
        });


    </script>

@endsection

resources/views/menu/show.blade.php
@extends('layouts.admin')


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2> Menu Details
                            <a class="btn btn-primary" style="float:right;" href="{{ route('menu.index') }}">
                                Back</a>
                        </h2>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Menu Name:</strong>
                        {{$menu->name}}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Link Type:</strong>
                        {{$menu->link_type}}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Status:</strong>
                        @if($menu->is_active)
                            Active
                        @else
                            In Active
                        @endif

                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Sort Order:</strong>
                        {{$menu->sort_order}}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Created At:</strong>
                        {{ date('M j, Y h:ia', strtotime($menu->created_at))}}
</div>
</div>
</div>


</div>
</section>
@endsection