routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Authentication Routes & Registration Routes
Auth::routes();
Route::get('get-services', 'ServicesController@getServices');
//Route::get('get-pages', 'PagesController@getPages');

$backendRoutes = function () {

    Route::get('/', 'HomeController@dashboard')->middleware('auth');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => ['auth']], function () {

        Route::get('profile/{user}', 'UserController@profile')->name('profile.view');
        Route::post('profile/{user}', 'UserController@profileUpdate')->name('profile.edit');
        Route::post('profile_image_upload/{user}', 'UserController@profileImageUpload')->name('profile.upload');
        
        Route::get('/dashboard', 'HomeController@dashboard');
        Route::resource('roles', 'RoleController');
        Route::resource('users', 'UserController');
        Route::resource('services', 'ServicesController');
        Route::get('get-all-services', 'ServicesController@getAllServices');


        // Blog Routes
        Route::resource('categories', 'CategoryController', ['except' => ['create']]);
        Route::resource('tags', 'TagController', ['except' => ['create']]);
        Route::resource('posts', 'PostController');

        // Customers
        Route::resource('customers', 'CustomersController');
        Route::get('get-customers', 'CustomersController@getCustomers');

        // Menu
        Route::resource('menu', 'MenuController');
        Route::get('get-menus', 'MenuController@getMenus');

    });
};

$frontendRoutes = function () {
    Route::get('/', 'DemoController@getHome');
    Route::get('/request_demo', 'DemoController@getDemoRequestForm');
    Route::post('/submit_demo_request', 'DemoController@postDemoRequest');
};


Route::group(['domain' => Config::get('app.domains.admin'), 'middleware' => []], $backendRoutes);
Route::group(['domain' => Config::get('app.domains.website'), 'middleware' => []], $frontendRoutes);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta NAME="robots" CONTENT="noindex,nofollow">

    <link rel="icon" type="image/png" sizes="32x32" href="{{ URL::asset('images/favicon.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ URL::asset('images/favicon.png') }}">


    <title>Admin Portal</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ mix('css/master.css') }}">
    <script src="{{ mix('/js/master.js') }}"></script>
    <script src="{{ asset('js/utils.js') }}"></script>
    @yield('css')

</head>

<body class="hold-transition sidebar-mini">
    <div class="loading" style="display:none">
        <div class="spinner"></div>
    </div>
    <div class="wrapper">

        <!-- Navbar -->
        @include('layouts.top_header')
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        @include('layouts.left_menu')
        <!-- /.Main Sidebar Container -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    <i class=""></i> @yield('parentModuleTitle')
                    <small>@yield('childModuleTitle')</small>
                </h1>
                <ol class="breadcrumb" style="display: none;">
                    <li><a href="{{route('home')}}"><i class="fas fa-home"></i> Home</a></li>
                    @yield('parentModule')
                    @yield('childModule')
                    <li class="active">@yield('activeModule')</li>
                </ol>
            </section>
            @yield('content')
        </div>
        <!-- /.content-wrapper -->


        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    @yield('js')

</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="icon" type="image/png" sizes="32x32" href="{{ URL::asset('images/favicon-logo.svg') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ URL::asset('images/favicon-logo.svg') }}">

    <title>Amsat Admin Portal</title>
    <!-- <title>{{ config('app.name', 'Laravel') }}</title> -->

    <link rel="stylesheet" href="{{ mix('css/master.css') }}">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm topLoginBar">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Admin Portal
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            {{--                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>--}}
                            {{--<a class="nav-link" href="{{ route('signin') }}">{{ __('Login') }}</a>--}}
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            {{--                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
                            {{--@if(request()->getHost() == config("app.domains.cockpit"))--}}
                            {{--@else--}}
{{--                            <a class="nav-link" href="{{ route('signup') }}">{{ __('Register') }}</a>--}}
                            {{--@endif--}}

                        </li>
                        @endif
                        @else
                        <!-- <li><a class="nav-link" href="{{ route('users.index') }}">Manage Users</a></li>
                            <li><a class="nav-link" href="{{ route('roles.index') }}">Manage Role</a></li>
                            <li><a class="nav-link" href="{{ route('products.index') }}">Manage Product</a></li> -->
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->email }} dedsd <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 loginContentBox">
            @yield('content')
        </main>
    </div>
    <script src="{{ mix('/js/master.js') }}"></script>

    @yield('js')
</body>

</html>

resources/views/layouts/app_old_original.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/left_menu.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/dashboard" class="brand-link">
        <span class="logo-mini">
            <img src="{{ asset('images/logo.png') }}" alt="Amsat" class="brand-image" style="width:30%;height:10%;">
        </span>
        {{--<span class="logo-lg">--}}
        {{--<img src="{{ asset('images/black.png') }}" alt="Amsat" class="brand-image" style="">--}}
        {{--</span>--}}
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item {{ Request::is('dashboard') ? 'active' : '' }}">
                    <a href="{{ URL::to('dashboard') }}" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Home</p>
                    </a>
                </li>
                @can('user-list')
                    <li class="nav-item has-treeview {{ (Request::is('users') || Request::is('roles')) ? 'active menu-open' : '' }}">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-user-cog"></i>
                            <p>
                                User Management
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">

                            <li class="nav-item {{ Request::is('users') ? 'active' : '' }}">
                                <a href="{{ URL::to('users') }}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Users</p>
                                </a>
                            </li>

                            @can('role-list')
                                <li class="nav-item {{ Request::is('roles') ? 'active' : '' }}">
                                    <a href="{{ URL::to('roles') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Roles</p>
                                    </a>
                                </li>
                            @endcan

                            @can('customer-list')
                                <li class="nav-item {{ Request::is('customer') ? 'active' : '' }}">
                                    <a href="{{ URL::to('customers') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Customers</p>
                                    </a>
                                </li>
                            @endcan

                        </ul>
                    </li>

                @endcan

                @can('blog-list')
                    <li class="nav-item has-treeview {{ (Request::is('blog') ) ? 'active menu-open' : '' }}">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-blog"></i>
                            {{--<i class="fas fa-blog"></i>--}}
                            <p>
                                Blog
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            @can('post-list')
                            <li class="nav-item {{ Request::is('posts') ? 'active' : '' }}">
                                <a href="{{ URL::to('posts') }}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    {{--<i class="fas fa-sim-card"></i>--}}
                                    <p>Post</p>
                                </a>
                            </li>
                            @endcan
                            @can('category-list')
                                <li class="nav-item {{ Request::is('categories') ? 'active' : '' }}">
                                    <a href="{{ URL::to('categories') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        {{--<i class="fas fa-album-collection"></i>--}}
                                        <p>Category</p>
                                    </a>
                                </li>
                            @endcan

                            @can('tag-list')
                                <li class="nav-item {{ Request::is('tags') ? 'active' : '' }}">
                                    <a href="{{ URL::to('tags') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        {{--<i class="fas fa-tags"></i>--}}
                                        <p>Tag</p>
                                    </a>
                                </li>
                            @endcan

                        </ul>
                    </li>

                @endcan

                @if(auth()->user()->can('services-list') )
                    <li class="nav-item {{ Request::is('services') ? 'active' : '' }}">
                        <a href="{{ URL::to('services') }}" class="nav-link">
                            <i class="fas fa-business-time nav-icon"></i>
                            {{--<i class="fas fa-business-time"></i>--}}
                            <p>Services</p>
                        </a>
                    </li>

                @endif

                @can('menu-list')
                    <li class="nav-item {{ Request::is('services') ? 'active' : '' }}">
                        <a href="{{ URL::to('menu') }}" class="nav-link">
                            <i class="fas fa-business-time nav-icon"></i>
                            {{--<i class="fas fa-business-time"></i>--}}
                            <p>Menu Management</p>
                        </a>
                    </li>

                @endcan


                @if(auth()->user()->can('page-list') )
                    <li class="nav-item {{ Request::is('pages') ? 'active' : '' }}">
                        <a href="{{ URL::to('pages') }}" class="nav-link">
                            <i class="fas fa-pager nav-icon"></i>
                            {{--<i class="fas fa-pager"></i>--}}
                            <p>Pages</p>
                        </a>
                    </li>

                @endif

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/top_header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
{{--  <form class="form-inline ml-3">--}}
{{--   <div class="input-group input-group-sm">--}}
{{--      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">--}}
{{--      <div class="input-group-append">--}}
{{--        <button class="btn btn-navbar" type="submit">--}}
{{--          <i class="fas fa-search"></i>--}}
{{--        </button>--}}
{{--      </div>--}}
{{--   </div>--}}
{{--  </form>--}}

<!-- Right navbar links -->
    <ul class="navbar-nav ml-auto topCustomNav">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user-lock"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="/profile/{{ Auth::user()->id }}" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="/dist/img/user.png" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                {{ Auth::user()->name ?? '' }}
                            </h3>
                            <p class="text-md text-muted">{{ Auth::user()->email ?? '' }}</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>

                <div class="dropdown-divider"></div>
                <a href="{{ route('logout') }}"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                   class="dropdown-item dropdown-footer"><i class=""></i>Logout</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
        {{--<li class="nav-item MobileNone loggedLink">--}}
          {{--<span>Logged in as:</span>--}}
          {{--<a href="http://localhost:8000/admin-u-1.html" target="_blank">admin</a>--}}
          {{--<a href="/profile/{{ Auth::user()->id }}" class="">--}}
              {{--@if(Auth::user()->name != '')--}}
                    {{--{{ Auth::user()->name }}--}}
              {{--@else {{ Auth::user()->email }}--}}
              {{--@endif</a>--}}

        {{--</li>--}}
        {{--<li class="nav-item">--}}
            {{--<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="nav-link logoutLink">--}}
                {{--<i class=""></i>Logout--}}
            {{--</a>--}}
            {{--<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
                {{--@csrf--}}
            {{--</form>--}}
        {{--</li>--}}
    </ul>
</nav>